name: Deploy to Pages
on: 
  push:
    branches: [master]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build & Deploy Vue
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Build
        run: |
          npm install
          npm run buildprod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: dist
